apply plugin: "java"

version '1.0'

sourceSets.main.java.srcDirs = ["src"]

repositories{
    mavenCentral()

    ivy{
        url = 'https://github.com/'
        patternLayout{artifact '/[organisation]/[module]/releases/download/[revision]/dependencies.jar'}
        metadataSources{ artifact() }
    }

    ivy{
        url = 'https://github.com/'
        patternLayout{artifact '/[organisation]/[module]/releases/[revision]/download/dependencies.jar'}
        metadataSources{ artifact() }
    }

    ivy{
        url = 'https://github.com/'
        patternLayout{artifact '/[organisation]/[module]/releases/download/master/[revision].jar'}
        metadataSources{ artifact() }
    }
}

java{
    targetCompatibility = JavaVersion.VERSION_17
    sourceCompatibility = JavaVersion.VERSION_17
}

ext{
    mindustryVersion = "v159.7"
}

dependencies{
    compileOnly mindustryVersion == "be" ? "Anuken:MindustryBuilds:latest" : "Anuken:Mindustry:$mindustryVersion"
    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
}

test {
    useJUnitPlatform()
}
