name: mod-pr

on: [pull_request]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up PATH
        run: |
          echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Run Spotless Check
        run: ./gradlew spotlessCheck
      - name: Build mod jar
        run: ./gradlew :mod:deploy
      - name: Upload built jar file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }} Pull Request
          path: mod/build/libs/${{ github.event.repository.name }}.jar
